// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrG9NprxnAaBshxqiieH22EkIQ98uQLi4',
    appId: '1:461547996397:web:669e2a779ab4b5de70f8e4',
    messagingSenderId: '461547996397',
    projectId: 'focusshift-de5e0',
    authDomain: 'focusshift-de5e0.firebaseapp.com',
    storageBucket: 'focusshift-de5e0.firebasestorage.app',
    measurementId: 'G-YV8P2ZHHN7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8NxbSBthpNODG8ii_01qpqUi-JIPoEl8',
    appId: '1:461547996397:ios:37c6db0619de263970f8e4',
    messagingSenderId: '461547996397',
    projectId: 'focusshift-de5e0',
    storageBucket: 'focusshift-de5e0.firebasestorage.app',
    iosBundleId: 'com.example.focusShift',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq84xVMWVYBQMAx5bP6Z35XgdW3Oa_u9A',
    appId: '1:461547996397:android:8b41dae097a4be6170f8e4',
    messagingSenderId: '461547996397',
    projectId: 'focusshift-de5e0',
    storageBucket: 'focusshift-de5e0.firebasestorage.app',
  );

}